# Generated by Django 4.2.13 on 2024-07-05 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football_camp', '0002_service_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='training',
            field=models.CharField(blank=True, choices=[('skills', 'Skills'), ('fitness', 'Fitness'), ('tactics', 'Tactics'), ('all', 'All')], max_length=10, null=True),
        ),
    ]
