# Generated by Django 4.2.13 on 2024-07-05 20:26

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('football_camp', '0003_alter_service_training'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'verbose_name': 'Booking', 'verbose_name_plural': 'Bookings'},
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'verbose_name': 'Player', 'verbose_name_plural': 'Players'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Booking Date'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football_camp.player', verbose_name='Player'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football_camp.service', verbose_name='Service'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='player',
            name='age',
            field=models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(14)], verbose_name='Player Age'),
        ),
        migrations.AlterField(
            model_name='player',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=6, verbose_name='Player Gender'),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Player Name'),
        ),
        migrations.AlterField(
            model_name='service',
            name='duration',
            field=models.CharField(max_length=100, verbose_name='Service Duration'),
        ),
        migrations.AlterField(
            model_name='service',
            name='features',
            field=models.TextField(verbose_name='Service Features'),
        ),
        migrations.AlterField(
            model_name='service',
            name='focus',
            field=models.CharField(max_length=200, verbose_name='Service Focus'),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Service Title'),
        ),
        migrations.AlterField(
            model_name='service',
            name='training',
            field=models.CharField(blank=True, choices=[('skills', 'Skills'), ('fitness', 'Fitness'), ('tactics', 'Tactics'), ('all', 'All')], max_length=10, null=True, verbose_name='Training Type'),
        ),
    ]
