# Generated by Django 4.2.13 on 2024-07-06 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football_camp', '0004_alter_booking_options_alter_player_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_details', models.TextField()),
            ],
        ),
    ]
