# Generated by Django 4.2.13 on 2024-07-07 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football_camp', '0005_trainingschedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='service',
        ),
        migrations.AddField(
            model_name='booking',
            name='services',
            field=models.ManyToManyField(to='football_camp.service', verbose_name='Services'),
        ),
    ]
